// app/layout.js
import { El_Messiri , Inter, Aref_Ruqaa_Ink } from "next/font/google"; // Importa Aref_Ruqaa_Ink
import "./globals.css";
import  WhatsApp  from "./WhatsappPedido";


const elMessiri = El_Messiri({
  subsets: ['arabic', 'latin'], // Incluye el subconjunto árabe si lo necesitas
  weight: ['400', '700'], // Define los pesos de fuente que usarás
  variable: '--font-el-messiri', // Crea esta variable CSS
  display: 'swap',
});



// Define Aref_Ruqaa_Ink para el logo del Navbar
const arefRuqaaInk = Aref_Ruqaa_Ink({
  subsets: ["arabic", "latin"], // Incluye el subconjunto árabe si lo necesitas para otros textos
  weight: ["400", "700"], // Aref Ruqaa Ink tiene dos pesos
  variable: '--font-aref-ruqaa-ink', // Nueva variable CSS
  display: 'swap',
});

// Puedes definir otra fuente global si lo deseas, como Inter para el resto del texto
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: "PERFUMES",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Aplica las variables CSS a la etiqueta <html>
    <html lang="en" className={` ${elMessiri.variable} ${arefRuqaaInk.variable} ${inter.variable}`}>
      <body>
        {/* Tu Navbar se renderiza aquí */}
        {children}
        <WhatsApp/>
      </body>
    </html>
  );
}