const perfumes = [
    {
      id: 1,
      title: "Bayaan Lattafa",
      description: "EDP| 100 ml",
      brand: "Lattafa",
      price: 80000,
      img: "/perfumes/12.png",
      imgHover: "/perfumes/8.jpg",
      gender: "Mujer",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/bayaan-3.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/bayaan-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/bayaan-2.jpg",
      nota1:"Bayaan de Lattafa es una fragancia de la familia olfativa Floral Frutal Gourmand para Mujeres. Las Notas de Salida son grosellero negro, lichi y pimienta rosa; las Notas de Corazón son rosa, cardamomo y praliné; las Notas de Fondo son musgo, madera de oud y vainilla. Sumérgete en la exquisita esencia de Bayaan, una fragancia femenina que desata la sensualidad. Con sus cautivadoras notas de grosellero negro, lichi y pimienta rosa, Bayaan es una sinfonía de elegancia y pasión. La mezcla única de rosa, cardamomo y praliné crea una experiencia olfativa inolvidable, mientras que el musgo y la madera de oud añaden un toque de misterio y sofisticación. Envuélvete en la seductora calidez de la vainilla, que deja una estela duradera de feminidad empoderada. Descubre la esencia de tu ser con Bayaan y despierta tu lado más intrigante. ¡Con Bayaan, la verdadera seducción nunca ha sido tan cautivadora!",
      nota2:"",
      nota3:"",

    },
    
    {
      id: 3,
      title: "Monarch Red Tobacco ",
      description: "EDP | 100 ml",
      brand: "Emper Perfumes",
      price: 85000,
      gender: "Unisex",
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/Fotos-pagina.pptx-19.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/tobacco-4.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/tobacco-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/tobacco-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/tobacco-3.jpg",
      nota1:"Notas altas: La fragancia se abre con una explosión de vigorizantes notas cítricas, que incluyen bergamota y mandarina. Estas notas altas frescas y estimulantes brindan una introducción vibrante y enérgica, preparando el escenario para el aroma rico y lujoso que seguirá.",
      nota2:"Notas de corazón: En el corazón de “MILESTONE Monarch Red Tobacco Vanilla Unisex”, se desarrolla una exquisita mezcla de hojas de tabaco rojo y especias aromáticas. Esta combinación de notas ahumadas y cálidas añade profundidad y complejidad, evocando una sensación de intriga y sofisticación.",
      nota3:"Notas de fondo: La fragancia concluye con una base sensual y aterciopelada, donde el encanto de la vainilla ocupa un lugar central. La dulzura cremosa de la vainilla se complementa con toques de ámbar y almizcle, creando una estela seductora y persistente que cautiva los sentidos.",
    },
   
    {
      id: 4,
      title: "Cocktail Intense",
      description: "EDP | 100 ml",
      brand: "Fragance World",
      price: 95000,
      gender: "Unisex",
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/Fotos-pagina.pptx-5.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/coctail-6.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/cocktail-5.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/cocktail-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/cocktail-3.jpg",
      nota1:"En sus notas de salida se despliega un refinado acorde de coñac que te envuelve con su calidez y profundidad. A este vigorizante comienzo se suman delicadas notas de vainilla y canela, aportando dulzura y complejidad.",
      nota2:"En el corazón de esta fragancia se revelan misteriosas notas orientales que añaden un encanto oriental exótico y profundo. Aquí, los acordes especiados se entrelazan sutilmente, dándole carácter e intensidad.",
      nota3:"Finalmente, en las notas de fondo, el ámbar y el almizcle se fusionan para crear un final duradero, embriagador y seductor.",
    },
    {
      id: 5,
      title: "Stallion 53 ",
      description: "EDP | 100 ml",
      brand: "Emper Perfumes",
      gender: "Unisex",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/02/Fotos-pagina.pptx-39.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/02/stallion-53-1.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/02/stallion-53-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/02/stallion-53-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/02/stallion-53-4.jpg",
      nota1:"STALLION 53 by Emper es una fragancia de la familia olfativa floral amaderada para hombres y mujeres. Notas Salida: Violeta y cardamomo; Notas medias: Íris y ámbar; Notas de fondo: Sándalo, cuero, papiro y ámbar. Stallion 53 es una fragancia irresistiblemente sensual que despierta la pasión con cada nota. La combinación exquisita de violeta, cardamomo y iris crea una experiencia olfativa única y cautivadora. El ámbar y el sándalo añaden un toque cálido y seductor, mientras que el cuero y el papiro aportan un matiz intrigante y misterioso. Esta fragancia es perfecta para aquellos que buscan destacar su atractivo y confianza. Sumérgete en el poder de Stallion 53 y deja que tu presencia hable por sí misma: un aroma que enciende la llama de la seducción!!!",
      nota2:"",
      nota3:"",
    },
      {
      id: 6,
      title: "Petra",
      description: "EDP | 100 ml",
      brand: " Lattafa",
      gender: "Unisex",
      price: 105000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2025/07/Perfumes-Decants-69.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2025/07/petra-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2025/07/petra-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2025/07/petra-3.jpg",
      img4:"",
      nota1:"Petra de Lattafa Perfumes es una fragancia de la familia olfativa Floral Frutal Gourmand para Hombres y Mujeres. Esta fragancia es nueva. Petra se lanzó en 2025. Las Notas de Salida son ron y ciruela; las Notas de Corazón son nardos y coco; las Notas de Fondo son vainilla, praliné y almizcle.",
      nota2:"",
      nota3:"",
    },
    {
      id: 7,
      title: "Bade’e Al Oud Honor & Glory",
      description: "EDP | 100 ml",
      brand: " Lattafa",
       gender: "Unisex",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/Perfumes-Decants-31.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/honor-1.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/honor-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/honor-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/honor-4.jpg",
      nota1:"Bade’e Al Oud Honor & Glory de Lattafa Perfumes es una fragancia de la familia olfativa para Hombres y Mujeres. Esta fragancia es nueva. Bade’e Al Oud Honor & Glory se lanzó en 2023. Las Notas de Salida son piña y créme brulée; las Notas de Corazón son canela, benjuí, cúrcuma (azafrán de la India) y pimienta negra; las Notas de Fondo son vainilla, cachemira, sándalo y musgo.",
      nota2:"",
      nota3:"",
    },
    {
      id: 8,
      title: "Haya",
      description: "EDP | 100 ml",
      brand: " Lattafa",
       gender: "Mujer",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/Patitas-Suaves-1-x-1-2.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/hata-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/haya-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/haya-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/haya-4.jpg",
      nota1:"Haya de Lattafa es una fragancia de la familia olfativa frutal floral para Mujeres. Las Notas de Salida son champaña, fresa, naranja sanguina, rosa y naranja tangerina; las Notas de Corazón son gardenia, jazmín y orquídea de vainilla; las Notas de Fondo son sándalo, ámbar y castaña.",
      nota2:"",
      nota3:"",
    },
    {
      id: 9,
      title: "Leen",
      description: "EDP | 100 ml",
      brand: " Lattafa",
      gender: "Unisex",
      price: 80000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/Fotos-pagina.pptx-14.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/leen-4.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/leen-3.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/leen-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/leen1-.jpg",
      nota1:"Leen de Lattafa es una fragancia de la familia olfativa floral fresca para Hombres y Mujeres. Las Notas de Salida son bergamota, jengibre, pimienta rosa y cúrcuma; las Notas de Corazón son pimienta negra, jazmín, mango, nardo y osmanto; las Notas de Fondo son incienso, almizcle y sándalo. Sumérgete en la irresistible fragancia de Leen, una experiencia olfativa que te envuelve con la chispeante combinación de bergamota, jengibre y pimienta rosa. La audaz incorporación de cúrcuma y pimienta negra añade un toque vibrante, mientras que las notas florales de jazmín, mango y nardo te transportan a un jardín exuberante. La sutileza del osmanto y la profundidad del incienso se entrelazan en armonía, mientras que la base de almizcle y sándalo deja una estela duradera de elegancia. Con Leen, cada gota es un recordatorio de tu autenticidad y poder interior. Descubre la esencia que te distingue y desata tu verdadera grandeza. ¡Leen, donde la sofisticación y la audacia se encuentran para crear una presencia inolvidable!",
      nota2:"",
      nota3:"",
    },
    {
      id: 10,
      title: "Eternal Oud",
      description: "EDP | 100 ml",
      brand: "Lattafa",
        gender: "Unisex",
      price: 90000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/03/Fotos-pagina.pptx-44.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/03/eternal-oud-web-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/eternal-oud-web-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/eternal-oud-web-5.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/eternal-oud-web-3-1-1.jpg",
      nota1:"Eternal Oud de Lattafa Perfumes es una fragancia de la familia olfativa Ámbar para Hombres y Mujeres.",
      nota2:"",
      nota3:"",
    },
    {
      id: 11,
      title: "Meethaq Extrait De Rouge",
      description: "EDP | 100 ml",
      brand: "Ard Al Zaafaran",
      gender: "Mujer",
      price: 70000,
      img: "https://emiratesoud.co.uk/cdn/shop/files/Meethaq-Extrait-De-Rouge-Perfume-100ml-EDP-by-Ard-Al-Zaafaran-169958472.jpg?v=1750902893&width=600",
      imgHover: "https://www.intenseoud.com/cdn/shop/files/4_e299dbcc-2c82-46e9-9005-1dc72fde4171.jpg?v=1729633508",
       img2:"",
      img3:"",
      img4:"",
      nota1:"Esta fragancia ofrece una mezcla dulce y reconfortante, que se abre con la delicada elegancia floral del azahar, aportando una atmósfera fresca y romántica. En el corazón, el delicioso malvavisco aporta una dulzura suave y etérea que resulta a la vez juguetona y placentera. La base de absoluto de vainilla crea un final cálido y cremoso, redondeando la fragancia con un encanto suave y decadente. Perfecta para quienes disfrutan de una fragancia gourmand ligera, dulce e irresistiblemente acogedora.",
      nota2:"",
      nota3:"",
    },
    {
      id: 12,
      title: "Shahama",
      description: "EDP | 100 ml",
      brand: "Matin & Martin",
        gender: "Hombre",
      price: 90000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/04/Perfumes-Decants-7.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/04/shahama-2.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/shahama-4.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/shahama-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/shahama-3.jpg",
      nota1:"SHAHAMA EAU DE PARFUM de Matin Martin es una fragancia de la familia olfativa Ámbar para Hombres. SHAHAMA EAU DE PARFUM se lanzó en 2021. Las Notas de Salida son notas afrutadas, notas especiadas y notas ozónicas; las Notas de Corazón son madera de oud, clavel y geranio; las Notas de Fondo son cuero, notas amaderadas y Notas balsámicas. Shahama es una fragancia masculina cautivadora y adictiva que fusiona notas afrutadas, especiadas y ozónicas para crear una experiencia olfativa única. Con la presencia distintiva de madera de oud, clavel y geranio, esta fragancia emana una masculinidad elegante y sofisticada. Los acordes de cuero y notas amaderadas aportan profundidad y calidez, mientras que las notas balsámicas añaden un toque de misterio y seducción. Shahama es la elección perfecta para el hombre moderno que busca destacar con un aroma inolvidable y envolvente. Deja que sus notas cautivadoras te envuelvan en un aura de misterio y sofisticación, haciéndote destacar en cualquier ocasión!!!",
      nota2:"",
      nota3:"",
    },
    
    {
      id: 14,
      title: "Al Qiam Gold",
      description: "EDP | 100 ml",
      brand: "Lattafa",
       gender: "Unisex",
      price: 80000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/Fotos-pagina.pptx-9.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/01/qiam-gold-2.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/qiam-gold-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/qiam-gold-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/qiam-gold-4.jpg",
      nota1:"https://perfumescardales.com.ar/wp-content/uploads/2024/01/qiam-gold-4.jpg",
      nota2:"",
      nota3:"",
    },
     {
      id: 15,
      title: "Musaman",
      description: "EDP | 100 ml",
      brand: "Lattafa",
       gender: "Unisex",
      price: 90000,
      img: "https://cdn.awsli.com.br/2500x2500/2667/2667788/produto/300789381/f1769e729733fdb8e0d86624223eba4d-w6p8hfw3kd.jpg",
      imgHover: "https://i0.wp.com/lujoperfume.com/wp-content/uploads/2024/03/Musamam-White-Intense-100-Ml-3.4-oz-EDP-by-Lattafa-2.png?fit=1080%2C1080&ssl=1",
       img2:"",
      img3:"",
      img4:"",
      nota1:"",
      nota2:"",
      nota3:"",
    },
    {
      id: 16,
      title: "Yara Candy",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Mujer",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/10/Perfumes-Decants-55.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/10/yara-candy-2.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/10/yara-candy-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/10/yara-candy-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/10/yara-candy-4.jpg",
      nota1:"Yara Candy de Lattafa Perfumes es una fragancia de la familia olfativa Floral Frutal Gourmand para Mujeres. Esta fragrancia es nueva. Yara Candy se lanzó en 2024. Las Notas de Salida son grosellas negras y Mandarina verde; las Notas de Corazón son Strawberry Fizz Candy y gardenia; las Notas de Fondo son vainilla, ámbar, sándalo y almizcle",
      nota2:"",
      nota3:"",
    },
     {
      id: 17,
      title: "Yara Tous",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Mujer",
      price: 70000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/11/Perfumes-Decants-25.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/11/yara-tous-4.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/11/yara-tous-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/11/yara-toous-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/11/yara-tous-3.jpg",
      nota1:"Yara Tous de Lattafa Perfumes es una fragancia de la familia olfativa para Mujeres. Esta fragrancia es nueva. Yara Tous se lanzó en 2023. Las Notas de Salida son mango, coco y maracuyá (fruta de la pasión); las Notas de Corazón son jazmín, heliotropo y flor de azahar del naranjo; las Notas de Fondo son vainilla, almizcle y cachemira.",
      nota2:"",
      nota3:"",
    },
     {
      id: 18,
      title: "Ramz Gold",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 70000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/05/Perfumes-Decants-56.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/05/ramz-gold-2.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/ramz-gold-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/ramz-gold-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/ramz-gold-4.jpg",
      nota1:"Ramz Lattafa (Gold) de Lattafa Perfumes es una fragancia de la familia olfativa frutal amaderada para Hombres y Mujeres. Las Notas de Salida son manzana, durazno, pera, naranja dulce y grosellas negras; las Notas de Corazón son jazmín sambac, rosa y flor de azahar del naranjo; las Notas de Fondo son sándalo, vainilla, almizcle blanco y pachulí. Ramz Gold es una fragancia embriagadora que captura la esencia del lujo y la pasión. La dulzura de la manzana, durazno y pera se funde con la frescura de la naranja dulce y grosellas negras, creando una apertura irresistible. En el corazón, el jazmín sambac, la rosa y la flor de azahar del naranjo despliegan un bouquet floral exótico y seductor. El fondo de sándalo, vainilla, almizcle blanco y pachulí aporta una calidez cremosa y envolvente, dejando una estela duradera que hipnotiza y fascina!!!",
      nota2:"",
      nota3:"",
    },
    {
      id: 19,
      title: "Nasheet",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 80000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/Perfumes-Decants-12.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/nasheet-4.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/nasheet-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/nasheet-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/nasheet-3.jpg",
      nota1:"Nasheet de Lattafa es una fragancia de la familia olfativa Amaderada Aromática para Hombres y Mujeres. La Nota de Salida es madera de gaiac; la Nota de Corazón es nuez moscada; las Notas de Fondo son Incienso, sándalo y cachemira. Nasheet de Lattafa redefine la sensualidad con una fragancia cautivadora que deja una huella inconfundible. La madera de gaiac establece un fondo magnético, mientras la nuez moscada agrega un toque picante, despertando la pasión. El incienso y el sándalo dan vida a una danza mística de aromas, creando un ambiente envolvente y seductor. La suavidad de la cachemira completa esta experiencia sensorial, dotando a Nasheet de una elegancia sensual incomparable. Sumérgete en la indulgencia de esta fragancia, donde cada nota es una invitación a explorar la profundidad de tu propia sensualidad!!!",
      nota2:"",
      nota3:"",
    },
     {
      id: 20,
      title: "Reyna",
      description: "EDP | 100 ml",
      brand: "Maison Alhambra",
      gender: "Mujer",
      price: 65000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2022/10/11-1.png",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/reyna-3.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/reyna-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/reyna-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/reyna-4.jpg",
      nota1:"Reyna de Maison Alhambra es un perfume perteneciente a la familia olfativa Floral Frutal Gourmand orientado para el público femenino.",
      nota2:"Notas de Salida: mandarina, bergamota y toronja (pomelo)",
      nota3:"Notas de Corazón: flor de azahar del naranjo, frambuesa y grosellas negras Notas de Fondo: crema batida, malvavisco (bombón), almizcle y almizcle ambreta",
    },
     {
      id: 21,
      title: "Kismet",
      description: "EDP | 100 ml",
      brand: "Maison Alhambra",
      gender: "Mujer",
      price: 60000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/02/Fotos-pagina.pptx-46.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/02/kismet-web-3.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/02/kismet-web1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/02/kismet-web-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/02/kismey-web-4-acordes.jpg",
      nota1:"Kismet for Women Edp de Maison Alhambra es una fragancia de la familia olfativa Oriental floral para Mujeres.",
      nota2:"",
      nota3:"",
    },
    {
      id: 22,
      title: "A La Rose",
      description: "EDP | 100 ml",
      brand: "Zimaya",
      gender: "Mujer",
      price: 70000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/08/Fotos-pagina.pptx-2.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/08/a-la-rose-3.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/08/a-la-rose-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/08/a-la-rose-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/08/a-la-rose-4.jpg",
      nota1:"A la Rose By Zimaya es una fragancia de la familia olfativa oriental floral para mujeres. Notas de salida: Floral blanco, jazmín, rosa, amaderado, almizcle; Notas de corazón: Osmanto, Narciso, Nectarina, Fresia; Notas de fondo: Tuberosa, ámbar, cedro, almizcle, sándalo.",
      nota2:"",
      nota3:"",
    },
     {
      id: 23,
      title: "Sakeena",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Mujer",
      price: 70000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/Patitas-Suaves-1-x-1-3.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2023/10/sakeena-1.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/sakeena-4.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/sakeena-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/10/sakeena-2.jpg",
      nota1:"Sakeena de Lattafa es una fragancia de la familia olfativa Floral Frutal Gourmand para Mujeres. Las Notas de Salida son maracuyá, notas ozónicas y mandarina; las Notas de Corazón son frambuesa, rosa, flor de azahar del naranjo y sal de mar; las Notas de Fondo son praliné, almizcle, vainilla y tófe. Sakeena de Lattafa es una fragancia cautivadora que seduce con su compleja mezcla de notas olfativas",
      nota2:"",
      nota3:"",
    },
     {
      id: 24,
      title: "Bade al Oud Noble Blush",
      description: "EDP | 100 ml",
      brand: "Al Haramain",
      gender: "Mujer",
      price: 100000,
      img: "https://www.hites.com/dw/image/v2/BDPN_PRD/on/demandware.static/-/Sites-mastercatalog_HITES/default/dwa0a76a29/images/original/pim/958609001/958609001_1.jpg?sw=1000&sh=1000",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/12/noble-blush-1.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/noble-blush-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/noble-blush-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/noble-blush-4.jpg",
      nota1:"Noble Blush de Lattafa es una fragancia de la familia olfativa Floral Frutal Gourmand para Mujeres. Esta fragancia es nueva, se lanzó en 2024. La Nota de Salida es Rose Milk; las Notas de Corazón son merengue, almendra; las Notas de Fondo son vainilla, sándalo y almizcle.",
      nota2:"",
      nota3:"",
    },
    {
      id: 25,
      title: "Masa",
      description: "EDP | 100 ml | Tester",
      brand: "Lattafa",
      gender: "Unisex",
      price: 105000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/04/Perfumes-Decants-69.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-15-at-13.47.12-1.jpeg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-15-at-13.47.11.jpeg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-15-at-13.47.12-2.jpeg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-15-at-13.47.12.jpeg",
      nota1:"Masa de Lattafa Perfumes es una fragancia de la familia olfativa Floral Frutal para Hombres y Mujeres. Las Notas de Salida son mango, azafrán, limón y pimienta rosa; las Notas de Corazón son hojas de violeta, jengibre, flor de azahar del naranjo y osmanto; las Notas de Fondo son Notas minerales, gamuza, ámbar y pachulí. Masa es un elixir embriagador, un baile cautivador de exuberancia y sofisticación. En su esencia, el mango y el limón entrelazan una danza tropical, mientras el azafrán y la pimienta rosa tejen un telar de especias ardientes sobre tu piel. Las hojas de violeta y el jengibre acarician con su frescura, como una brisa en la noche. La flor de azahar del naranjo y el osmanto revelan un corazón floral, llenando el aire con su dulzura embriagadora. Las notas minerales y la gamuza añaden profundidad, como la tierra húmeda bajo la luna. Ámbar y pachulí cierran la experiencia, envolviéndote en un abrazo cálido y duradero!!!",
      nota2:"",
      nota3:"",
    },
      {
      id: 26,
      title: "Saher Al Layali",
      description: "EDP | 100 ml",
      brand: "Ard Al Zaafaran",
      gender: "Mujer",
      price: 70000,
      img: "https://http2.mlstatic.com/D_NQ_NP_712410-MLA86801206832_072025-O.webp",
      imgHover: "https://www.numonday.com/wp-content/uploads/2025/04/ambientbeauty-s-l1600.webp",
       img2:"https://www.intenseoud.com/cdn/shop/files/4_b3a1022c-66ef-4e32-9f81-3e05e92bf3f6_large.jpg?v=1718231099",
      img3:"https://m.media-amazon.com/images/I/514bs60lyFL._UF1000,1000_QL80_.jpg",
      img4:"",
      nota1:"La fragancia se abre con una vibrante y estimulante mezcla de manzana fresca y pimienta rosa picante. El corazón revela una composición única y aromática de lavanda, piña y haba tonka. La fragancia se asienta sobre una base profunda y lujosa de ámbar, cuero, pachulí y vainilla. El ámbar aporta una calidez resinosa que envuelve los sentidos, mientras que el cuero añade un toque audaz y sofisticado. El pachulí aporta un matiz ligeramente dulce, y la vainilla completa la mezcla con su suave y reconfortante dulzura.",
      nota2:"",
      nota3:"",
    },
    {
      id: 27,
      title: "24 Carat Pure Gold",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 70000,
      img: "https://acdn-us.mitiendanube.com/stores/004/407/494/products/24-carat-pure-gold-ca96d52eda561859d317177700264133-1024-1024.webp",
      imgHover: "https://aromatica.cr/cdn/shop/files/24-Carat-Pure-Gold-EDT-para-hombre-100-ml-Aromatica-CR-275152664.jpg?v=1735755810&width=416",
       img2:"https://leparfumpr.com/cdn/shop/files/GOLD_1800x1800.webp?v=1709913993",
      img3:"https://m.media-amazon.com/images/I/514bs60lyFL._UF1000,1000_QL80_.jpg",
      img4:"https://aromatica.cr/cdn/shop/files/24-Carat-Pure-Gold-EDT-para-hombre-100-ml-Aromatica-CR-275152772.jpg?v=1735755812&width=990",
      nota1:"Lattafa 24 Carat Pure Gold es una fragancia oriental lujosa que fusiona especias cálidas con elementos amaderados y resinosos.",
      nota2:"La apertura es intensa y especiada, donde la canela y el azafrán crean un dúo cálido y exótico que se entrelaza con la profundidad resinosa del oud.",
      nota3:"El corazón revela un contraste elegante entre la rosa, que aporta un toque floral romántico y sofisticado, y el sándalo, que proporciona una cremosidad amaderada que suaviza las especias intensas de la apertura.",
    },

    // 2da tanda de perfumes

     {
      id: 28,
      title: "Amber Oud Gold",
      description: "EDP | 100 ml",
      brand: "AL HARAMAIN",
      gender: "Unisex",
      price: 130000,
      img: "https://acdn-us.mitiendanube.com/stores/004/407/494/products/amber-oud-gold-60ml-d3fdd9b347e5e3cfa517159077075416-1024-1024.webp",
      imgHover:"https://http2.mlstatic.com/D_NQ_NP_644752-MLA77088660696_062024-O.webp",
      img2:"",
      img3:"https://acdn-us.mitiendanube.com/stores/003/581/838/products/imagen-de-whatsapp-2025-02-28-a-las-15-06-02_e4a5feed-d3d377192f4934792f17407663708793-1024-1024.jpg",
      img4:"https://images.fravega.com/f500/b1b77907399815dbf4178a4e4831b444.jpg",
      nota1:"",
      nota2:"",
      nota3:""
    },
      {
      id: 29,
      title: "Rayhaan Elixir",
      description: "EDP | 100 ml",
      brand: "Rayhaan",
      gender: "Unisex",
      price: 90000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2025/07/Perfumes-Decants-19.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2025/07/RAYHAAN-3.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2025/07/RAYHAAN2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2025/07/RAYHAAN-1.jpg",
      img4:"",
      nota1:"Rayhaan Elixir de Rayhaan es una fragancia de la familia olfativa Oriental Amaderada para Hombres y Mujeres. Esta fragrancia es nueva. Rayhaan Elixir se lanzó en 2024. Las Notas de Salida son menta y bergamota; las Notas de Corazón son benjuí y lavanda; las Notas de Fondo son vainilla y haba tonka.",
      nota2:"",
      nota3:""
    },
      {
      id: 30,
      title: "Club De Nuit Lionheart Man",
      description: "EDP | 100 ml",
      brand: "Armaf",
      gender: "Hombre",
      price: 110000,
      img: "https://acdn-us.mitiendanube.com/stores/004/407/494/products/lioheart-man-4fdacfc21b1fdbd64c17503545153244-1024-1024.webp",
      imgHover:"https://http2.mlstatic.com/D_NQ_NP_756868-MLA86116884930_062025-O.webp",
       img2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe71KQLlUGGibjkfzEySKTThpGnr-L9n8o8w&s",
      img3:"https://http2.mlstatic.com/D_NQ_NP_756868-MLA86116884930_062025-O.webp",
      img4:"",
      nota1:"Club De Nuit Lionheart Man de Armaf es una fragancia audaz y carismática que equilibra lo clásico con un giro moderno y seductor. Su apertura combina la lavanda aromática con la frescura vibrante de la menta, creando una sensación energizante y masculina. En el corazón, el dúo de benjuí y vainilla aporta calidez resinosa y dulzura envolvente, preparando el terreno para un fondo profundamente sensual. Las notas de tabaco, miel y haba tonka conforman una base rica, ambarada y adictiva que deja una estela intensa y memorable. Ideal para noches frescas o eventos especiales, esta fragancia proyecta confianza y sofisticación.",
      nota2:"",
      nota3:""
    },
    {
      id: 31,
      title: "Smoked Oud & Vanilla",
      description: "EDP | 100 ml",
      brand: "Maison Alhambra",
      gender: "Unisex",
      price: 70000,
      img: "https://acdn-us.mitiendanube.com/stores/004/407/494/products/smoked-oud-vanilla-c63533fe960da730e117418027686878-1024-1024.jpg",
      imgHover:"https://static.wixstatic.com/media/d2932e_0cded7d8563046fabfbf733bb0ebaee6~mv2.png/v1/fill/w_560,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/d2932e_0cded7d8563046fabfbf733bb0ebaee6~mv2.png",
      img2:"https://fragrances.com.ng/media/catalog/product/cache/0daeb07bb1d294c1f281fab47369d56a/m/a/maison_al_hambra_smoked_oud_vanilla_edp_100ml-3.jpg",
      img3:"",
      img4:"",
      nota1:"",
      nota2:"",
      nota3:""
    },
    
      {
      id: 33,
      title: "Khamrah",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 100000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/07/Fotos-pagina.pptx-1.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/khamra-3.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/khamra-4.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/khamrah-1.jpg",
      img4:"",
      nota1:" ",
      nota2:"",
      nota3:""
    },
        {
      id: 34,
      title: "Odyssey Homme Black",
      description: "EDP | 100 ml",
      brand: "Armaf",
      gender: "Hombre",
      price: 90000,
      img: "https://nrperfumesarabes.com/cdn/shop/files/IMG-5653.png?v=1735232443",
      imgHover:"https://acdn-us.mitiendanube.com/stores/004/347/554/products/tienda-f9a33e9b8a3534509117488983909595-1024-1024.jpg",
      img2:"https://fimgs.net/photogram/p180/4u/mc/IV0xXyIBSrWKEBBx.jpg",
      img3:"https://orientedistribuidora.com.ar/wp-content/uploads/2024/12/3-28.jpg",
      img4:"",
      nota1:"Odyssey Homme de Armaf es una fragancia de la familia olfativa Oriental para Hombres. Las Notas de Salida son vainilla y ámbar; las Notas de Corazón son notas orientales, especias y iris; las Notas de Fondo son vainilla, cuero y jazmín.",
      nota2:"",
      nota3:""
    },
      {
      id: 35,
      title: "Bharara Chocolate",
      description: "EDP | 100 ml",
      brand: "Bharara",
      gender: "Unisex",
      price: 120000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2025/03/Perfumes-Decants-75.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2025/03/bahara-chocolate-3.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2025/03/bahara-chocolate-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2025/03/baharara-chocolate-1.jpg",
      img4:"",
      nota1:"Bharara Chocolate de Bharara es una fragancia de la familia cálida especiada para hombres y mujeres",
      nota2:"",
      nota3:""
    },
     {
      id: 36,
      title: "Taureau De Combat",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Hombre",
      price: 105000,
      img: "https://orientaldream.b-cdn.net/9512-large_default/lattafa-pride-taureau-de-combat-edp-100ml.jpg",
      imgHover:"https://oasisperfumesusa.com/cdn/shop/files/Taureau_De_Combat_5.jpg?v=1755896828&width=1024",
      img2:"https://i0.wp.com/frencharabianperfume.com/wp-content/uploads/1-29.png?fit=2000%2C2000&ssl=1",
      img3:"https://www.intenseoud.com/cdn/shop/files/3_f8bc47e5-ba45-48d1-ad1e-043226e9c30a.webp?v=1755554296",
      img4:"",
      nota1:"Bharara Chocolate de Bharara es una fragancia de la familia cálida especiada para hombres y mujeres",
      nota2:"",
      nota3:""
    },
      {
      id: 37,
      title: "Nitro Red",
      description: "EDP | 100 ml",
      brand: "Dumont",
      gender: "Hombre",
      price: 95000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/06/Perfumes-Decants-2024-06-29T190844.960.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2024/06/nitro-red-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/06/nitro-red-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/06/nitro-red-3.jpg",
      img4:"",
      nota1:"Nitro Red de Dumont es una fragancia de la familia olfativa Aromática Frutal para Hombres. Las Notas de Salida son manzana, lavanda y bergamota; las Notas de Corazón son sandía, cedro y cálamo aromático; las Notas de Fondo son ámbar, sándalo y pachulí. Nitro Red es una fragancia que captura la esencia de la seducción pura. La jugosa manzana y la suave lavanda se entrelazan con la chispeante bergamota y la dulce sandía, creando un primer encuentro irresistible. A medida que la fragancia se desarrolla, el cedro robusto y el cálamo aromático aportan una profundidad intrigante. El ámbar cálido y el sándalo cremoso envuelven la piel en una caricia que hipnotiza. Finalmente, el pachulí terroso deja un rastro duradero y misterioso, haciendo de Nitro Red una experiencia olfativa inolvidable!!",
      nota2:"",
      nota3:""
    },
    {
      id: 38,
      title: "Qaed Al Fursan",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 80000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/03/Fotos-pagina.pptx-46.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/qaed-3.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/qaed-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/qaed-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/03/qaed-4.jpg",
      nota1:"Qaed Al Fursan de Lattafa es una fragancia de la familia olfativa Aromática floral amaderada para Hombres y Mujeres. Las Notas de Salida son piña y azafrán; las Notas de Corazón son jazmín y abeto balsámico; las Notas de Fondo son ámbar, cedro y madera de oud.",
      nota2:"Qaed Al Fursan de Lattafa es una fragancia cautivadora que despierta los sentidos con su intrigante combinación de notas. En su apertura, una explosión fresca y jugosa de piña se mezcla con la calidez del azafrán, creando una introducción irresistiblemente seductora.",
      nota3:""
    },
    {
      id: 39,
      title: "Asad",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Hombre",
      price: 80000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/04/Fotos-pagina.pptx-60.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2023/04/asad-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/04/asad-3.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/04/asad-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/04/asad-web-3.jpg",
      nota1:"Asad de Lattafa es una fragancia unisex lanzada en 2021, conocida por su durabilidad y versatilidad. Combina notas de pimienta negra, tabaco y piña al inicio, seguidas de café, pachulí e iris, y finaliza con un fondo cálido de vainilla, ámbar y maderas secas. Comparada a menudo con Sauvage Elixir de Dior, Asad ofrece una experiencia similar a un precio más accesible​ .",
      nota2:"Asad de Lattafa Perfumes es una fragancia de la familia olfativa Ámbar para Hombres. Asad se lanzó en 2021.",
      nota3:""
    },
     {
      id: 40,
      title: "Jean Lowe Inmortal",
      description: "EDP | 100 ml",
      brand: "Maison Alhambra",
      gender: "Hombre",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/07/Fotos-pagina.pptx-28.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/inmortal-3.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/lowe-inmortal-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/inmortal-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2023/07/lowe-inmortal-3.jpg",
      nota1:"Jean Lowe Immortal de Maison Alhambra es una fragancia de la familia olfativa Ámbar para Hombres. Las Notas de Salida son pomelo, jengibre y bergamota; las Notas de Corazón son notas acuáticas, romero, salvia y geranio; las Notas de Fondo son ambroxan, ládano y ámbar. Jean Lowe Immortal de Maison Alhambra es una fragancia que evoca la eterna atracción masculina, cautivando los sentidos desde el primer instante.",
      nota2:"",
      nota3:""
    },
    {
      id: 41,
      title: "Club de nuit Intense",
      description: "EDP | 100 ml",
      brand: "Armaf",
      gender: "Hombre",
      price: 90000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2021/08/dc6cb5_2d9b45e73ce94f95bb60ac40bd8a94b1mv2.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2020/01/club-de-nuit-man-edt-4.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2020/01/club-de-nuit-man-edt-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2020/01/club-de-nuit-man-edt-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2020/01/club-de-nuit-edt-5.jpg",
      nota1:"Club de Nuit Edt Intense Man de Armaf es una fragancia de la familia olfativa Amaderada Especiada para Hombres.",
      nota2:"",
      nota3:""
    },
    {
      id: 42,
      title: "Amber Oud Aqua Dubai",
      description: "EDP | 100 ml",
      brand: "Al Haramain",
      gender: "Unisex",
      price: 130000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/12/Perfumes-Decants-21.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/aqua-dubai-1.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/aqua-dubai-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/12/aqua-dubai-3.jpg",
      img4:"",
      nota1:"Amber Oud Aqua Dubai de Al Haramain es una fragancia de la familia olfativa Aromática Frutal para Hombres y Mujeres. Esta fragancia es nueva, se lanzó en 2024. Las Notas de Salida son bergamota, mandarina, notas verdes; las Notas de Corazón son ámbar, melón, grosellas negras, piña; las Notas de Fondo son almizcle, petit grain, gálbano y vainilla",
      nota2:"",
      nota3:""
    },
     {
      id: 43,
      title: "L’aventure Fraiche",
      description: "EDP | 100 ml",
      brand: "Al Haramain",
      gender: "Unisex",
      price: 90000,
      img: "https://acdn-us.mitiendanube.com/stores/005/620/060/products/al_haramain_l_adventure_fraiche_800x-6dc3c6fe5c7d84a4aa17513044253583-1024-1024.webp",
      imgHover:"https://i0.wp.com/lorens.com.co/wp-content/uploads/Laventure-Fraiche-de-Al-Haramain-hombre-flyer.jpg?resize=700%2C700&ssl=1",
      img2:"https://i0.wp.com/lorens.com.co/wp-content/uploads/Laventure-Fraiche-de-Al-Haramain-hombre-flyer-2.jpg?resize=700%2C700&ssl=1",
      img3:"https://i0.wp.com/lorens.com.co/wp-content/uploads/Laventure-Fraiche-de-Al-Haramain-hombre-botella.jpg?resize=700%2C700&ssl=1",
      img4:"",
      nota1:"El perfume LAventure Fraiche de Al Haramain es una fragancia unisex que destaca por su frescura, energía y sofisticación. Perteneciente a la familia olfativa Aromática Cítrica, esta fragancia se lanzó en 2024 y ha capturado los sentidos de quienes buscan un perfume versátil y duradero.",
      nota2:"Esta fragancia LAventure Fraiche es perfecta para cualquier estación del año, y su carácter fresco la convierte en una excelente opción tanto para el día como para la noche. La locion LAventure Fraiche no solo ofrece una experiencia olfativa inolvidable, sino que también viene en un elegante frasco que refleja su espíritu dinámico y moderno.",
      nota3:""
    },
     {
      id: 44,
      title: "Hawas Fire",
      description: "EDP | 100 ml",
      brand: "Rasasi",
      gender: "Unisex",
      price: 130000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2025/02/Perfumes-Decants-58.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2025/02/hawas-fire-4.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2025/02/hawas-fire-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2025/02/hawas-fire-2.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2025/02/hawas-fire-3.jpg",
      nota1:"Hawas Fire de Rasasi es una fragancia de la familia olfativa Aromática Acuática para Hombres. Esta fragancia es nueva, se lanzó en 2025. La Nota de Salida es esclarea; las Notas de Corazón son jazmín egipcio, Notas marinas; las Notas de Fondo son ámbar, ámbar gris y Notas minerales.",
      nota2:"",
      nota3:""
    },
      {
      id: 45,
      title: "Asad Bourbon",
      description: "EDP | 100 ml",
      brand: "Lattafa",
      gender: "Unisex",
      price: 90000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2025/01/Perfumes-Decants-8.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2025/01/asad-bourbon-2.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2025/01/asad-bourbon-1.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2025/01/asad-bourbon-3.jpg",
      img4:"",
      nota1:"Asad Bourbon de Lattafa es una fragancia de la familia olfativa Oriental Especiada para Hombres",
      nota2:"",
      nota3:""
    },
    {
      id: 46,
      title: "Odissey Tyrant",
      description: "EDP | 100 ml",
      brand: "Armaf",
      gender: "Hombre",
      price: 95000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/09/Perfumes-Decants-39.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2024/09/tyrant-4.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/09/tyrant-3.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/09/tyrant-1.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/09/tyrant-2.jpg",
      nota1:"Odyssey Tyrant Special Edition de Armaf es una fragancia de la familia olfativa Oriental Amaderada para Hombres. Las Notas de Salida son pomelo, cítricos; las Notas de Corazón son geranio, pimienta, elemí, lavanda; las Notas de Fondo son ambroxan, vetiver, cedro y notas amaderadas. Odyssey Tyrant es una declaración de poder y seducción, una fragancia que envuelve al hombre audaz en un aura de misterio.",
      nota2:"La frescura vibrante del pomelo y los cítricos se entrelaza con la intensidad de la pimienta, despertando un deseo irrefrenable. En el corazón, el geranio y la lavanda aportan un equilibrio sofisticado, revelando la complejidad de un verdadero conquistador. Las notas amaderadas y el vetiver añaden una profundidad seductora, mientras que el ambroxan crea una estela que perdura en la memoria.",
      nota3:"Cada aplicación es un recordatorio de que la fuerza y el magnetismo pueden ser irresistibles. Odyssey Tyrant no solo desafía, seduce y captura la atención, convirtiendo cada momento en una experiencia inolvidable. Asume tu papel de tirano y deja tu huella en el mundo!!!"
    },
     {
      id: 47,
      title: "Bharara King",
      description: "EDP | 100 ml",
      brand: "Bharara",
      gender: "Hombre",
      price: 120000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2023/12/Perfumes-Decants-15.jpg",
      imgHover:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/bharara-3.jpg",
      img2:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/bharara-4.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2023/12/bharara1.jpg",
      img4:"",
      nota1:"King de Bharara es una fragancia de la familia olfativa Aromática para Hombres. Las Notas de Salida son naranja, limón y bergamota; la Nota de Corazón es notas afrutadas; las Notas de Fondo son vainilla, almizcle blanco y ámbar.",
      nota2:"",
      nota3:""
    },



  ];
  export default perfumes;

  /*
{
      id: 2,
      title: "French Avenue",
      description: "EDP | 100 ml",
      brand: "Venus De Milo",
      price: 100000,
      img: "https://acdn-us.mitiendanube.com/stores/002/708/808/products/arabe-2025-07-19t161958-136-32dfc0a2b515e645a217529539838864-1024-1024.png",
      imgHover: "https://http2.mlstatic.com/D_NQ_NP_847626-MLA89161293347_082025-O.webp",
      gender: "Mujer",
      img2:"",
      img3:"",
      img4:"",
      nota1:"",
      nota2:"",
      nota3:"",

    },

    {
      id: 13,
      title: "Amber Wave",
      description: "EDP | 100 ml",
      brand: "Matin & Martin",
      gender: "Mujer",
      price: 75000,
      img: "https://perfumescardales.com.ar/wp-content/uploads/2024/05/Perfumes-Decants-23.jpg",
      imgHover: "https://perfumescardales.com.ar/wp-content/uploads/2024/05/amber-wave-1.jpg",
       img2:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/amber-wave-2.jpg",
      img3:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/amber-wave-3.jpg",
      img4:"https://perfumescardales.com.ar/wp-content/uploads/2024/05/amber-wave-4.jpg",
      nota1:"AMBER WAVE EAU DE PARFUM de Matin Martin es una fragancia de la familia olfativa Ámbar Amaderada para Hombres y Mujeres. Las Notas de Salida son azafrán y naranja; las Notas de Corazón son cuero, gamuza, azúcar y jazmín; las Notas de Fondo son cuero, ambroxan y ámbar. Sumérgete en el hechizo cautivador de Amber Wave, una sinfonía olfativa que despierta la pasión y el deseo más profundo. El azafrán y la naranja entrelazan sus notas en una danza tentadora, mientras el cuero y la gamuza añaden una sensualidad ahumada y misteriosa. El toque dulce del azúcar es como un susurro seductor en el aire, mientras que el jazmín despliega su aroma floral con elegancia y poder. El ambroxan y el ámbar envuelven la piel en un abrazo cálido y envolvente, dejando una estela adictiva que perdura en la memoria, invitando a explorar sus profundidades una y otra vez. Déjate envolver por la seducción etérea de Amber Wave y descubre el poder de tu magnetismo interior!!",
      nota2:"",
      nota3:"",
    },
  */